### ISSUE TITLE
lc每日报错

### ISSUE THREAD

**Issue by NanakoOfficial** [Nranphy/nonebot_plugin_leetcode2#1]
报错内容为
f.write(today_data[2])
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 261: illegal multibyte sequence

**Comment by Nranphy** [comment]
原因在于文件编码有误，请尝试在出错代码上方的open函数中加入参数 `encoding="UTF-8-sig"` ，或对 `today_data[2]` 字符串编码为 UTF-8

这个插件是咱刚学 Python 时写的，近期有计划重构，还请继续关注，谢谢！！

**Comment by NanakoOfficial** [comment]
> 原因在于文件编码有误，请尝试在出错代码上方的open函数中加入参数 `encoding="UTF-8-sig"` ，或对 `today_data[2]` 字符串编码为 UTF-8
> 
> 这个插件是咱刚学 Python 时写的，近期有计划重构，还请继续关注，谢谢！！

很好的插件！辛苦了

**Comment by Nranphy** [comment]
> 很好的插件！辛苦了

感谢支持！！
