### ISSUE TITLE
安装时出现error

### ISSUE THREAD

**Issue by Laurc2004** [Nranphy/nonebot_plugin_leetcode2#2]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nonebot-plugin-acm-reminder 0.1.4 requires httpx>=0.23.3, but you have httpx 0.20.0 which is incompatible.
nonebot-plugin-acm-reminder 0.1.4 requires nonebot-plugin-apscheduler>=0.2.0, but you have nonebot-plugin-apscheduler 0.1.4 which is incompatible.
nonebot-plugin-acm-reminder 0.1.4 requires nonebot-plugin-htmlrender>=0.2.0.3, but you have nonebot-plugin-htmlrender 0.0.4.8 which is incompatible.
nonebot-plugin-resolver 1.0.11 requires httpx<0.24,>=0.23, but you have httpx 0.20.0 which is incompatible.
![image](https://user-images.githubusercontent.com/119660750/222464616-6d660ba2-e0f4-4311-b040-3e4daba5c73a.png)

**Comment by Laurc2004** [comment]
![image](https://user-images.githubusercontent.com/119660750/222466294-ccc33b32-0e69-4e3e-ba6d-9bdc311674cc.png)
使用了pip install httpx==0.23.3安装

**Comment by Nranphy** [comment]
插件太久没有维护才产生的问题…
前者是插件依赖仍然为旧版本，但一般情况下依赖的新版本也能兼容，直接手动安装新版本依赖并将插件放入插件文件夹可以解决
后者是**使用了较旧版本的本插件**，已不适配新版本的nonebot2。这是可能是图一中插件更新失败导致的，可以尝试上述方法手动更新插件后再启动bot。
本插件的问题大概只在于没有更新.toml中的依赖版本，我将在之后进行更新，也欢迎各位的pr。在仓库更新后，我会再次回复并关闭本issues。

**Comment by Laurc2004** [comment]
![)NPA6YN`KG5N5% (C%)R{XU](https://user-images.githubusercontent.com/119660750/224674172-1390d71f-2e72-462a-9bb0-e723d491f8da.png)
安装完运行就出现问题了，麻烦看看
