### ISSUE TITLE
如何安装最新版？我好像还是旧版

### ISSUE THREAD

**Issue by Laurc2004** [Nranphy/nonebot_plugin_leetcode2#3]
![XUKST069_59QVL8699`0%J1](https://user-images.githubusercontent.com/119660750/224675120-3c1e8cd1-b828-4714-b674-7e97bacc274c.png)
麻烦看看

**Comment by Nranphy** [comment]
已在PYPI发版，现可通过 `pip install --upgrade nonebot_plugin_leetcode2` 进行更新，或者直接克隆本仓库进行手动更新

（其实是我之前只更新了仓库，没更新PYPI。。）
![害怕捏](https://i.328888.xyz/2023/03/13/vuHYC.th.jpeg)

**Comment by Laurc2004** [comment]
![image](https://user-images.githubusercontent.com/119660750/224696704-fb867394-2862-445d-afbf-86d8b218bea3.png)
这是咋回事啊（枯了

**Comment by Nranphy** [comment]
（是我又弄错了...）
![呜呜呜](https://s1.ax1x.com/2023/03/13/ppQX3DA.jpg)

还是一样的指令，现在再试一次呢

**Comment by Laurc2004** [comment]
![image](https://user-images.githubusercontent.com/119660750/224700140-f45db23e-bdd1-4845-a4eb-68c9f41c4c8e.png)
还是老样子 giegie （枯了

**Comment by Nranphy** [comment]
我测试过，现在应该是行了的

要不你试试先卸载再安装？ `pip uninstall nonebot_plugin_leetcode2 && pip install nonebot_plugin_leetcode2`

**Comment by Laurc2004** [comment]
可以用了 感谢作者耐心回复
