### ISSUE TITLE
我又遇到新的问题了，nonebot-plugin-apscheduler导入失败

### ISSUE THREAD

**Issue by Laurc2004** [Nranphy/nonebot_plugin_leetcode2#4]
![image](https://user-images.githubusercontent.com/119660750/224714729-ed14ab1c-519d-489d-ac02-4a2d247fccba.png)
![image](https://user-images.githubusercontent.com/119660750/224714829-373854b0-6a8a-46d3-84cd-89e1a1db3b81.png)
麻烦作者大哥帮我看看，已star

**Comment by Nranphy** [comment]
报错没安装这插件。。看起来可能是你没安装到虚拟环境

issues也不方便，也算是和本插件无关的问题，可以来NoneBot官方交流群768887710再问问，大佬们的解答可比我的好（躺×

**Comment by Laurc2004** [comment]
版本问题，已解决。
