### ISSUE TITLE
centos系统中文不支持

### ISSUE THREAD

**Issue by qdwqsadwqds** [Nranphy/nonebot_plugin_leetcode2#5]
部署在centos7系统的该插件，在运行过程中出现了中文不显示的问题，如图所示：所有的中文文字都变成了方块
![3263193078-127180351-1C1D945044747F69573EF9A57ECDBCF6](https://user-images.githubusercontent.com/97772136/235877942-cdf1db40-3b55-480c-8ed9-ea5f940fe2a2.png)

**Comment by Nranphy** [comment]
系统缺少对应的中文字体，可以自行查询自己系统的字体安装方法
本插件转图片功能使用了[nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)，也可以去对应仓库查看文档中的解决方案（[readme底部](https://github.com/kexue-z/nonebot-plugin-htmlrender#centos-%E4%BD%BF%E7%94%A8-yum)）
